CREATE DATABASE courses;
USE courses;
CREATE TABLE courses (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(20), RATING FLOAT(20), NUMRATINGS INT(20));
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('CS1501', 2, 4);
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('CS250', 3, 5);
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('CS350', 5, 3);
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('M150', 5, 3);
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('M151', 5, 3);
INSERT INTO courses(NAME, RATING, NUMRATINGS) VALUES('M200', 5, 3);

CREATE TABLE comments (ID INT AUTO_INCREMENT PRIMARY KEY, COURSE_ID INT, COMMENT VARCHAR(10000), createdDate datetime DEFAULT CURRENT_TIMESTAMP);
